'use strict';

insightDashboardApp.controller('MainCtrl', ['$scope', function($scope) {
  $scope.data = [
      [
         "/install/jquery",
         "419"
      ],
      [
         "/install/backbone",
         "259"
      ],
      [
         "/install/bootstrap",
         "193"
      ],
      [
         "/install/angular",
         "177"
      ],
      [
         "/install/underscore",
         "105"
      ],
      [
         "/install/angular-ui",
         "69"
      ],
      [
         "/install/handlebars",
         "69"
      ],
      [
         "/install/requirejs",
         "58"
      ],
      [
         "/install/foundation",
         "55"
      ],
      [
         "/install/jquery-mobile",
         "54"
      ],
      [
         "/install/jade",
         "50"
      ],
      [
         "/install/lodash",
         "48"
      ],
      [
         "/install/jquery-ui",
         "47"
      ],
      [
         "/install/modernizr",
         "46"
      ],
      [
         "/install/ember",
         "44"
      ],
      [
         "/install/socket.io",
         "44"
      ],
      [
         "/install/angular-resource",
         "43"
      ],
      [
         "/install/d3",
         "42"
      ],
      [
         "/install/angular-bootstrap",
         "33"
      ],
      [
         "/install/font-awesome",
         "33"
      ],
      [
         "/install/threejs",
         "31"
      ],
      [
         "/install/compass",
         "29"
      ],
      [
         "/install/marionette",
         "28"
      ],
      [
         "/install/coffee-script",
         "26"
      ],
      [
         "/install/zepto",
         "22"
      ],
      [
         "/install/compass-twitter-bootstrap",
         "21"
      ],
      [
         "/install/fuelux",
         "21"
      ],
      [
         "/install/angularjs",
         "20"
      ],
      [
         "/install/jasmine",
         "20"
      ],
      [
         "/install/jquery-simpleweather",
         "20"
      ],
      [
         "/install/require",
         "20"
      ],
      [
         "/install/bootstrap-sass",
         "18"
      ],
      [
         "/install/layoutmanager",
         "18"
      ],
      [
         "/install/bootstrap-js",
         "17"
      ],
      [
         "/install/bootstrap.css",
         "17"
      ],
      [
         "/install/requirejs-text",
         "17"
      ],
      [
         "/install/backbone.localStorage",
         "15"
      ],
      [
         "/install/backbone.paginator",
         "15"
      ],
      [
         "/install/hogan",
         "14"
      ],
      [
         "/install/hundlebars",
         "14"
      ],
      [
         "/install/normalize-css",
         "14"
      ],
      [
         "/install/angular-complete",
         "13"
      ],
      [
         "/install/lawnchair",
         "11"
      ],
      [
         "/install/knockout",
         "10"
      ],
      [
         "/install/moment",
         "10"
      ],
      [
         "/install/select2",
         "10"
      ],
      [
         "/install/ace",
         "9"
      ],
      [
         "/install/angular-grid",
         "9"
      ],
      [
         "/install/angular-strap",
         "9"
      ],
      [
         "/install/coffeescript",
         "9"
      ]
   ];
}]);
